update the api key

diff --git a/.github/workflows/manual-trigger-actions.yml b/.github/workflows/manual-trigger-actions.yml
--- a/.github/workflows/manual-trigger-actions.yml
+++ b/.github/workflows/manual-trigger-actions.yml
@@ -83,6 +83,11 @@ jobs:
         run: |
           # Retrieve the new API key from Azure
           new_api_key=$(az ml online-endpoint show --name diabetesend --resource-group diabetes-dev-rg --workspace-name aml-diabetes-dev --query apiKey -o tsv)
+          exit_code=$?
+          if [ $exit_code -ne 0 ]; then
+            echo "Failed to retrieve API key from Azure with exit code $exit_code"
+            exit $exit_code
+          fi
           echo "New API Key: $new_api_key"
 
           # Update API key on Render
